#!/usr/bin/perl

use lib '.';
use Signature;

open SECRET, "<secret";
my $shared_secret = do { local $/; <SECRET> };

my $holdTerminator = $/;
undef $/;
open(displayfile, "<www.maths.warwick.ac.uk/maths/seminars/display.html") || die "www.maths.warwick.ac.uk/maths/seminars/display.html: $!\n";
my $data=<displayfile>;
close displayfile;
$/ = $holdTerminator;	



my $signer = Signature->new($shared_secret);

my $hash = $signer->sign($data);

print $hash;
