#!/bin/bash
#
# kiosk mode works fine except that it disables the keyboard and so
# is very hard to get out of! 
#
#/usr/bin/chromium-browser --kiosk file://www/display.html
#
# with --start-fullscreen one can kill the window with Alt-F4 and
# then Ctrl-c in the terminal window.
#
/usr/bin/chromium-browser --start-fullscreen --hide-scrollbars file://$HOME/screen/www/display.html &

# xprintidle returns the idle time in milliseconds
#
# xdotool simulates a keypress (the Home key here),
#   sending it to the window which matches some criterion.
#
# The following will cause the page view to return to the top after an
# interval of between 30+epsilon and 60-epsilon seconds.
#
while true; do
    if [ `xprintidle` -gt 30000 ]; then
	xdotool search --name "Warwick Mathematics Institute" key Home;
    fi;
    sleep 30
done
